version: '3.10'
services:
  db:
    container_name: dev_bd
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    command: ./node_modules/.bin/parcel watch bundles-src/index.js --dist-dir bundles --public-url="./"
    volumes:
      - static_volume:/Star-Burger/bundles
  web:
    container_name: backend
    build: .
    command: gunicorn star_burger.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/Star-Burger
      - media_volume:/Star-Burger/media
      - static_volume:/Star-Burger/static
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
      - frontend
  nginx:
    image: nginx:1.21-alpine
    volumes:
      - media_volume:/Star-Burger/media
      - static_volume:/Star-Burger/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
  media_volume:
