# Generated by Django 3.2 on 2022-06-30 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_remove_order_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_number',
            new_name='order',
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
    ]
