# Generated by Django 3.2 on 2022-07-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Необработанный', 'Необработанный'), ('Сборка', 'Сборка'), ('Доставка', 'Доставка'), ('Завершен', 'Завершен')], db_index=True, default='RAW', max_length=50, verbose_name='статус'),
        ),
    ]
