# Generated by Django 3.2 on 2022-07-11 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='call_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='дата и время звонка'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='дата и время доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='registration_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime.now, verbose_name='дата и время регистрации'),
            preserve_default=False,
        ),
    ]
