# Generated by Django 3.2 on 2022-07-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_order_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPositionRestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=500, verbose_name='адрес доставки')),
                ('lon', models.FloatField(verbose_name='долгота')),
                ('lat', models.FloatField(verbose_name='широта')),
            ],
            options={
                'verbose_name': 'координаты адресов заказов',
                'verbose_name_plural': 'координаты адреса заказа',
                'unique_together': {('lon', 'lat')},
            },
        ),
    ]
