# Generated by Django 3.2 on 2022-07-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0058_auto_20220720_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='lat',
            field=models.FloatField(default=1.0, verbose_name='широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lon',
            field=models.FloatField(default=1.0, verbose_name='долгота'),
            preserve_default=False,
        ),
    ]
