# Generated by Django 3.2 on 2022-08-29 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0063_auto_20220823_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_fulfilling_restaurant',
            new_name='fulfilling_restaurant',
        ),
    ]
