# Generated by Django 3.2 on 2022-08-29 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0064_rename_order_fulfilling_restaurant_order_fulfilling_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_total_cost',
            new_name='order_position_total_cost',
        ),
    ]
