# Generated by Django 3.2 on 2022-08-29 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0065_rename_order_total_cost_orderitem_order_position_total_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='call_time',
            new_name='call_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_time',
            new_name='delivery_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='registration_time',
            new_name='registration_at',
        ),
    ]
